site_name: CASTLE Docs

nav:
  - Home: index.md
  - About: about.md
  - Practices: practices.md
  - Equipment: equipment.md
  - PC Build: pc_build.md
  - Server: server.md
  - RAID Setup: raid_setup.md
  - Printer Setup: printer_setup.md
  - Scripts: scripts.md

extra_css:
  - style.css